name: Node.js Package
on:
  push:
    branches:
      - main
jobs:
  release-github:
    runs-on: ubuntu-latest
    # if: "startsWith(github.event.head_commit.message, '[RELEASE]')"
    permissions: 
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: ls -la